name: Test Python code

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Deps
        runs: |
          pip install -r AIMedicalBot-main/AIMedicalBot-main/requirements.txt
          pip install pytest

      - name: Test Code
        runs: |
          pytest