name: Test Python Code

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Deps
        run: |
          pip install -r AIMedicalBot-main/AIMedicalBot-main/requirements.txt
          pip install pytest

      - name: Test Code
        run: |
          pytest "./AIMedicalBot-main/AIMedicalBot-main/test_stt_img_ot.py"
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          
